const REQUIRED_SERVER_VARS = [
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'OPENAI_API_KEY',
] as const

// Provisioning-required for the PrioryxAI spec's Phase 1 features
// (GitHub OAuth App, Google OAuth, Claude, transactional email, analytics,
// error tracking, token encryption, and the ai-service link). None of
// these can be generated by an agent - the user must provision them.
const SPEC_REQUIRED_VARS = [
  'GITHUB_CLIENT_ID',
  'GITHUB_CLIENT_SECRET',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'ANTHROPIC_API_KEY',
  'RESEND_API_KEY',
  'ENCRYPTION_KEY',
  'AI_SERVICE_URL',
  'AI_SERVICE_SECRET',
] as const

const OPTIONAL_VARS = [
  'APIFY_TOKEN',
  'YOUTUBE_API_KEY',
  'ALFA_LEETCODE_API_URL',
  'CODING_PROFILE_SERVICE_URL',
  'RAZORPAY_KEY_ID',
  'RAZORPAY_KEY_SECRET',
  'RAZORPAY_WEBHOOK_SECRET',
  'POSTHOG_KEY',
  'SENTRY_DSN',
] as const

export function checkRequiredEnvVars(): void {
  const missing = REQUIRED_SERVER_VARS.filter(
    key => !process.env[key]
  )
  if (missing.length > 0) {
    console.error('[ENV ERROR] MISSING REQUIRED ENV VARS:', missing)
    // Don't throw in production — log and continue
    // But this will cause API failures
  }

  const missingOptional = OPTIONAL_VARS.filter(
    key => !process.env[key]
  )
  if (missingOptional.length > 0) {
    console.warn('[ENV WARN] Missing optional env vars:', missingOptional)
  }
}

/**
 * Throws a descriptive error listing every missing spec-required var.
 * Call this from a feature's entry point once that feature is wired up
 * (e.g. the GitHub OAuth route, the ai-service client) rather than at
 * global startup, since these are provisioned incrementally per Step 5-7
 * of the monorepo rebuild plan.
 */
export function assertSpecEnvVars(keys: readonly (typeof SPEC_REQUIRED_VARS)[number][]): void {
  const missing = keys.filter(key => !process.env[key])
  if (missing.length > 0) {
    throw new Error(
      `Missing required environment variable(s): ${missing.join(', ')}. ` +
      'See apps/web/.env.example for what each one is for.'
    )
  }
}

export function getEnvVar(key: string, fallback?: string): string {
  const val = process.env[key] ?? fallback
  if (!val) {
    console.error(`[ENV] Missing: ${key}`)
    return ''
  }
  return val
}
