/**
 * LLM Priority Planner — Phase 1
 *
 * Replaces the deterministic rule cascade in engine.ts with a single GPT-4o
 * reasoning call. The deterministic engine.ts is preserved as a fallback.
 *
 * Design:
 * - Collects signals from the same collectors as ai-planner.ts (untouched)
 * - Adds workload/burnout state from burnout-detector.ts (Phase 3 folded in)
 * - One GPT-4o call with response_format: json_object
 * - Per-user per-day Redis cache using the existing midnightISTttl() pattern
 * - Falls back to generatePriorityPlan() from engine.ts on any failure
 */

import { createClient } from '@/lib/supabase/server'
import { openai } from '@/lib/openai'
import { redis, withFallback, midnightISTttl } from '@/lib/redis'
import { generatePriorityPlan, PriorityPlan, PriorityTask } from './engine'
import { getBurnoutState } from './burnout-detector'
import { collectExamSignals } from './collectors/exam-collector'
import { collectDSASignals } from './collectors/dsa-collector'
import { collectGitHubSignals } from './collectors/github-collector'
import { collectResumeSignals } from './collectors/resume-collector'
import { collectProjectSignals } from './collectors/project-collector'
import { collectSubjectSignals } from './collectors/subject-collector'
import { buildUserContext } from '@/lib/context/user-context'
import { buildScopedAIContext } from '@/lib/ai/context-builder'

/** Extended plan that includes LLM reasoning fields */
export interface LLMPriorityPlan extends PriorityPlan {
  burnoutRisk: 'low' | 'medium' | 'high'
  burnoutNote: string | null
  todaysFocus: string
  /** true when this response was served from Redis cache */
  fromCache?: boolean
  /** true when this response was generated by the deterministic fallback */
  fromFallback?: boolean
}

const CACHE_PREFIX = 'priority:plan:v1'

/** JSON schema description embedded in system prompt for GPT-4o */
const RESPONSE_SCHEMA_DESCRIPTION = `
You MUST respond with a JSON object matching this EXACT schema — no extra fields, no markdown:
{
  "todaysFocus": "string — one punchy sentence on the single most important thing today",
  "burnoutRisk": "low" | "medium" | "high",
  "burnoutNote": "string or null — only set when burnoutRisk is medium/high; explain WHY you are reducing the workload and what to do instead",
  "urgentAlerts": ["string"],
  "insights": ["string — max 4 items"],
  "tasks": [
    {
      "id": "string — copy from the signal id if available, else generate a short unique slug",
      "title": "string",
      "category": "leetcode" | "hackerrank" | "project" | "resume" | "github" | "exam" | "job_application" | "learning",
      "priority": "CRITICAL" | "HIGH" | "MEDIUM" | "LOW",
      "estimatedMinutes": number,
      "actionUrl": "string or null",
      "actionLabel": "string or null",
      "tags": ["string"],
      "why": "string — explain this specific task (not generic)",
      "reasoning": "string — state the TRADE-OFF you made: what you deprioritised and why (e.g. 'exam is 3 days away, which normally would push DSA lower — but this graph problem is a direct exam topic, so keeping it')"
    }
  ]
}

Rules for task ranking:
- CRITICAL exam ≤ 2 days always goes first, no exceptions
- If burnoutRisk is "medium": max 5 tasks, reduce estimatedMinutes by 20%
- If burnoutRisk is "high": max 3 tasks, add a strong burnoutNote, ONLY include CRITICAL/HIGH tasks
- Each reasoning field must name the specific trade-off made, not repeat the "why" field
- Prefer tasks with high leverage (exam + DSA gap overlap) over isolated tasks
- Do NOT include duplicate task types unless genuinely different content
`

export async function generateLLMPlan(userId: string): Promise<LLMPriorityPlan> {
  const today = new Date()
  const todayISO = today.toISOString().split('T')[0]

  // ── 1. Check Redis cache (per-user per-day) ───────────────────────────
  const cacheKey = `${CACHE_PREFIX}:${userId}:${todayISO}`

  const cached = await withFallback<string | null>(
    () => redis.get<string>(cacheKey),
    null,
    800
  )

  if (cached) {
    try {
      const parsed = typeof cached === 'string' ? JSON.parse(cached) : cached
      return { ...parsed, fromCache: true }
    } catch {
      // Bad cached value — continue to regenerate
    }
  }

  // ── 2. Collect signals (collectors untouched per spec) ────────────────
  const supabase = createClient()

  const [profileRes, resumeProfileRes, lcProfileRes] = await Promise.allSettled([
    supabase
      .from('users')
      .select('stream, target_companies, display_name, name, subjects, semester')
      .eq('id', userId)
      .maybeSingle(),
    supabase
      .from('user_resumes')
      .select('skill_entities, swot')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle(),
    supabase
      .from('leetcode_profiles')
      .select('placement_readiness_score, ai_analysis, leetcode_username')
      .eq('user_id', userId)
      .maybeSingle(),
  ])

  const profile = profileRes.status === 'fulfilled' ? profileRes.value.data : null
  const resumeProfile =
    resumeProfileRes.status === 'fulfilled' ? resumeProfileRes.value.data : null
  const lcProfile =
    lcProfileRes.status === 'fulfilled' ? lcProfileRes.value.data : null

  const companies = (profile?.target_companies ?? []) as string[]
  const skills =
    (resumeProfile?.skill_entities as { skills?: string[] } | null)?.skills ?? []
  const lcWeakTopics =
    (
      lcProfile?.ai_analysis as {
        priority_topics?: Array<{ topic: string; priority: string }>
      } | null
    )?.priority_topics
      ?.filter((t) => t.priority === 'CRITICAL' || t.priority === 'HIGH')
      ?.map((t) => t.topic) ?? []
  const lcScore =
    (lcProfile as { placement_readiness_score?: number } | null)
      ?.placement_readiness_score
  const unifiedContextSummary = await buildUserContext(supabase, userId, {
    taskLimit: 10,
    includeFeedback: true,
  })
    .then((ctx) => buildScopedAIContext(ctx, 'priority'))
    .catch(() => 'Unified context unavailable.')

  // Run all signal collectors in parallel
  const [examRes, dsaRes, githubRes, resumeGapsRes, projectRes, subjectRes] =
    await Promise.allSettled([
      collectExamSignals(supabase, userId),
      collectDSASignals(supabase, userId, lcWeakTopics, companies, 5),
      collectGitHubSignals(supabase, userId),
      collectResumeSignals(supabase, userId, companies),
      collectProjectSignals(supabase, userId),
      collectSubjectSignals(supabase, userId),
    ])

  const exams = examRes.status === 'fulfilled' ? examRes.value : []
  const dsa = dsaRes.status === 'fulfilled' ? dsaRes.value : []
  const github = githubRes.status === 'fulfilled' ? githubRes.value : []
  const resumeGaps = resumeGapsRes.status === 'fulfilled' ? resumeGapsRes.value : []
  const projects = projectRes.status === 'fulfilled' ? projectRes.value : []
  const subjects = subjectRes.status === 'fulfilled' ? subjectRes.value : []

  // ── 3. Collect burnout / workload state (Phase 3) ─────────────────────
  const nearestExamDays = exams.length > 0 ? exams[0].daysUntil : null
  const workloadState = await getBurnoutState(supabase, userId, nearestExamDays)

  // ── 4. Build structured signal summary for LLM context ───────────────
  const signalContext = {
    userProfile: {
      name: profile?.name ?? profile?.display_name ?? 'Student',
      semester: profile?.semester,
      subjects: (profile?.subjects ?? []) as string[],
      targetCompanies: companies.slice(0, 3),
      lcScore,
      lcWeakTopics: lcWeakTopics.slice(0, 4),
      resumeSkillsCount: skills.length,
    },
    signals: {
      exams: exams.map((e) => ({
        id: e.id,
        subject: e.subjectName,
        daysUntil: e.daysUntil,
        priority: e.priority,
        urgencyScore: e.urgencyScore,
      })),
      dsa: dsa.slice(0, 5).map((d) => ({
        id: `dsa-${d.questionId}`,
        title: d.title,
        topic: d.topic,
        difficulty: d.difficulty,
        whyNow: d.whyNow,
        priority: d.priority,
        urgencyScore: d.urgencyScore,
        actionUrl: d.problemUrl,
      })),
      github: github.slice(0, 3).map((g) => ({
        id: `github-${g.repoName}`,
        repo: g.repoName,
        action: g.actionTitle,
        urgencyScore: g.urgencyScore,
        priority: g.priority,
        estimatedMinutes: g.estimatedMinutes,
        actionUrl: g.repoUrl,
      })),
      resumeGaps: resumeGaps.slice(0, 2).map((r) => ({
        id: `gap-${r.gapSkill}`,
        skill: r.gapSkill,
        urgencyScore: r.urgencyScore,
        priority: r.priority,
      })),
      projects: projects.slice(0, 2).map((p) => ({
        id: `project-${p.projectId}`,
        title: p.projectTitle,
        phase: `${p.currentPhase}/6`,
        urgencyScore: p.urgencyScore,
        priority: p.priority,
        actionUrl: `/career/foundry/project/${p.projectId}`,
      })),
      subjects: subjects.slice(0, 1).map((s) => ({
        id: `subject-${s.subject}`,
        subject: s.subject,
        urgencyScore: s.urgencyScore,
        priority: s.priority,
      })),
    },
    workloadState: workloadState.summary,
    workloadRiskScore: workloadState.riskScore,
    regionalContext: unifiedContextSummary,
    date: todayISO,
  }

  // ── 5. Call GPT-4o with full JSON schema enforcement ──────────────────
  let llmResult: LLMPriorityPlan | null = null

  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o',
      response_format: { type: 'json_object' },
      max_tokens: 2000,
      temperature: 0.3, // Low temp for consistent task ranking
      messages: [
        {
          role: 'system',
          content: `You are the reasoning core of PrioryxAI — a placement and academic success system for Indian engineering students. Your job is to take structured signals about a student's academic and career state and produce a ranked, justified daily action plan.

${RESPONSE_SCHEMA_DESCRIPTION}

You are reasoning about a student in semester ${signalContext.userProfile.semester ?? 'unknown'} targeting: ${signalContext.userProfile.targetCompanies.join(', ') || 'top tech companies'}.
Their LeetCode placement score is ${lcScore !== null && lcScore !== undefined ? `${lcScore}/100` : 'unknown — not connected'}.
Workload risk score: ${workloadState.riskScore}/100 (${workloadState.velocityTrend} velocity, ${workloadState.examPressure} exam pressure).
${workloadState.riskScore >= 70 ? '⚠️ HIGH BURNOUT RISK — dramatically reduce workload. Max 3 tasks. Include a burnoutNote.' : ''}
${workloadState.riskScore >= 45 && workloadState.riskScore < 70 ? '⚡ MEDIUM LOAD — moderate workload. Max 5 tasks.' : ''}`,
        },
        {
          role: 'user',
          content: `Today's signals:\n${JSON.stringify(signalContext, null, 2)}\n\nGenerate the ranked task plan.`,
        },
      ],
    })

    const raw = completion.choices[0]?.message?.content ?? ''
    const parsed = JSON.parse(raw)

    // Validate the structure before accepting
    if (!Array.isArray(parsed.tasks) || typeof parsed.todaysFocus !== 'string') {
      throw new Error('LLM returned invalid schema')
    }

    // Normalise tasks to match PriorityTask shape expected by frontend
    const tasks: PriorityTask[] = parsed.tasks.map(
      (t: {
        id?: string
        title?: string
        category?: string
        priority?: string
        estimatedMinutes?: number
        actionUrl?: string
        actionLabel?: string
        tags?: string[]
        why?: string
        reasoning?: string
      }, idx: number) => ({
        id: t.id ?? `llm-task-${idx}`,
        category: t.category ?? 'learning',
        title: t.title ?? 'Task',
        description: t.why ?? '',
        why: t.reasoning ?? t.why ?? '',
        estimatedMinutes: Number(t.estimatedMinutes) || 30,
        priority: (t.priority as PriorityTask['priority']) ?? 'MEDIUM',
        tags: t.tags ?? [],
        completed: false,
        scheduledFor: 'today',
        actionUrl: t.actionUrl ?? undefined,
        actionLabel: t.actionLabel ?? undefined,
      })
    )

    llmResult = {
      todaysTasks: tasks,
      urgentAlerts: Array.isArray(parsed.urgentAlerts) ? parsed.urgentAlerts : [],
      insights: Array.isArray(parsed.insights) ? parsed.insights.slice(0, 4) : [],
      generatedAt: new Date().toISOString(),
      burnoutRisk: parsed.burnoutRisk ?? 'low',
      burnoutNote: parsed.burnoutNote ?? null,
      todaysFocus: parsed.todaysFocus ?? '',
      fromCache: false,
      fromFallback: false,
    }

    // ── 6. Cache in Redis for rest of the day ───────────────────────────
    const ttl = midnightISTttl()
    await withFallback(
      () => redis.set(cacheKey, JSON.stringify(llmResult), { ex: ttl }),
      null,
      800
    )

    console.log(
      `[LLMPlanner] Generated plan for ${userId} — ${tasks.length} tasks, burnoutRisk: ${llmResult.burnoutRisk}`
    )
    return llmResult
  } catch (err) {
    console.error('[LLMPlanner] GPT-4o call failed, falling back to deterministic engine:', err)
  }

  // ── 7. Deterministic fallback — engine.ts untouched ──────────────────
  const fallback = await generatePriorityPlan(userId)
  return {
    ...fallback,
    burnoutRisk: workloadState.riskScore >= 70 ? 'high' : workloadState.riskScore >= 45 ? 'medium' : 'low',
    burnoutNote:
      workloadState.riskScore >= 45
        ? `Workload is elevated (${workloadState.totalPending} pending tasks, velocity: ${workloadState.velocityTrend}). Consider deferring lower-priority items.`
        : null,
    todaysFocus: fallback.urgentAlerts[0] ?? 'Focus on your highest-priority tasks today.',
    fromFallback: true,
  }
}
